image: node:22

definitions:
    caches:
        cache: ~/.cache
        gradle: ~/.gradle
    steps:
        - step: &release
              name: release
              caches:
                  - cache
              script:
                  - npx -p semantic-release -p @semantic-release/changelog -p @semantic-release/git semantic-release
        - step: &tests
              name: run-tests
              image: gradle:8.4-jdk17
              caches:
                  - gradle
              script:
                  - gradle test
              artifacts:
                  - sdk/build/reports/jacoco/**
                  - sdk/build/jacoco/**
        - step: &sonarcloud-analysis
              name: sonar
              caches:
                  - node
              clone:
                  depth: full # SonarCloud scanner needs the full history to assign issues properly
              script:
                  -   pipe: sonarsource/sonarcloud-scan:4.1.0
                      variables:
                          SONAR_SCANNER_OPTS: '-Dsonar.coverage.jacoco.xmlReportPaths=sdk/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml'
                  -   pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
    branches:
        master:
            - parallel:
                  - step: *release
            - step: *tests
            - step: *sonarcloud-analysis
    pull-requests:
        '**':
            - step: *tests
            - step: *sonarcloud-analysis
